version: "3.3"

services:
 mysqldb:
  container_name: mysqldb
  image: mysql
  restart: unless-stopped
  environment:
   MYSOL_ROOT_PASSWORD: sadok
  ports:
    - "3306:3306"
  volumes:
    - /home/mysql/data:/var/lib/mysql
 spring_app:
  image: gacharsadok/achat
  container_name: achat
  restart: on-failure
  ports:
    - 8089:8089
  depends_on:
    - mysqldb
  achatfront:
    image: gacharsadok/achatfront
    container_name: achatfront
    expose:
      - 4200
    links:
      - spring_app
    depends_on:
      - spring_app
    ports:
      - 4200:4200
    restart: on-failure

    command: "ng serve --open --host 192.168.1.8 --port 4200 --disable-host-check"
