version: "3.3"

services:
 mysqldb:
  container_name: mysqldb
  image: mysql
  restart: unless-stopped
  environment:
   MYSOL_ROOT_PASSWORD: sadok
  ports:
    - "3306:3306"
  volumes:
    - db:/var/lib/mysql
 spring_app:
  image: gacharsadok/achat
  container_name: achat
  restart: on-failure
  ports:
    - 8089:8089
  depends_on:
    - mysqldb
