version: "3.3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD= yes
      - MYSQL_DATABASE=achatdb
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: chadha14/achattp
    container_name: achattp
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    achatfront:
    image: chadha14/achatfront
    container_name: achatfront
    links:
      - spring_app
    depends_on:
      - spring_app
    ports:
    - "4200:80"

volumes:
  db:

