version: "3.3"

services:
 mysqldb:
  container_name: mysql
  image: mysql
  restart: unless-stopped
  environment:
   MYSOL_ROOT_PASSWORD: sadok
   MYSQL_DATABASE: 'achatdb'
  ports:
    - "3306:3306"
  volumes:
    - /home/mysql/data:/var/lib/mysql
 spring_app:
  image: gacharsadok/achat
  container_name: achat
  restart: on-failure
  ports:
    - 8089:8089
  environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
           "spring.datasource.username" : "root",
           "spring.datasource.password" : ,
           "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
           "spring.jpa.hibernate.ddl-auto" : "update"
         }'
  depends_on:
    - mysqldb
