version: "3.3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD= yes
      - MYSQL_DATABASE=achatdb
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  
  projetachatfront:
      image: gacharsadok/achatfront
      container_name: achatfront
      links:
        - app
      depends_on:
        - app
      ports:
        - 4200:80
volumes:
  db:
