version: "3.3"

services:
 mysqldb:
  container_name: mysqldb
  image: mysql
  restart: unless-stopped
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: 'achatdb'
  ports:
    - "3306:3306"
  volumes:
    - db:/var/lib/mysql
 spring_app:
  image: 79f61693a565 
  container_name: 9e053962beb4_achat
  restart: on-failure
  ports:
    - 8089:8089
  depends_on:
      - mysqldb
volumes:
   db:
