version: "3.3"

services:
 mysqldb:
  container_name: mysqldb
  image: mysql
  restart: unless-stopped
  environment:
   MYSQL_ROOT_PASSWORD: 'sadok'
   MYSQL_DATABASE: 'achatdb'
   MYSQL_USER: 'mysql'
   MYSQL_PASSWORD: 'sadok'
   MYSQL_ROOT_HOST: '%'
  ports:
    - "3306:3306"
  volumes:
    - db:/var/lib/mysql
 spring_app:
  depends_on:
    - mysqldb
  image: gacharsadok/achat
  container_name: achat
  restart: on-failure
  ports:
    - 8089:8089
   SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
        "spring.datasource.username" : "mysql",
        "spring.datasource.password" : "sadok",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  
 achatfront:
    image: gacharsadok/achatfront
    container_name: achatfront
    links:
      - spring_app
    depends_on:
      - spring_app
    ports:
      - 4200:80
volumes:
  db:
